### ISSUE TITLE
Lucene index generated from older version of MSR is not working in the newest version

### ISSUE THREAD

**Issue by oliverhaagh** [maritimeconnectivity/ServiceRegistry#62]
When running the latest version of the MSR with a Lucene index that was generated by an older version, the following errors will be thrown whenever doing a search:

```
2024-11-04T11:03:16.427Z ERROR 1 --- [mcp-service-registry] [io-8444-exec-65] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.hibernate.search.util.common.SearchException: HSEARCH000284: Unable to open index readers: Could not load codec 'Lucene95'. Did you forget to add lucene-backward-codecs.jar?
Context: indexes [Instance]] with root cause

java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene95' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene99]
...
```

This results in an HTTP 500 for the user.
Completely deleting the index, restarting the MSR and thus letting it regenerate the index seems to solve the issue.

**Comment by nvasta** [comment]
I think the best way to get rid of this is to completely delete the old indexes... the service will just regenerate new ones while it boots...

**Comment by nvasta** [comment]
That shouldn't happen if you run it an a container though... thew lucene indexes will be inside the container... what is the setup for this deployment?

**Comment by oliverhaagh** [comment]
We are running in a container, but mounting the index path to the host filesystem so we don't need to regenerate the index on every restart, as that can sometimes take quite a while, and I could imagine that others might want to do the same. I agree that the easiest solution is just to delete and regenerate the indexes, but that was not really obvious until getting the exception above.

**Comment by oliverhaagh** [comment]
As far as can tell from searching a bit around, it is possible to upgrade an index, but it needs to be done manually using the Lucene IndexUpgrader tool. Maybe we should just add a note in the README about that if you get Lucene related exceptions after upgrading the MSR it is recommended to delete the current indexes and let the MSR regenerate them?

**Comment by nvasta** [comment]
Agreed, I will do that then... btw maybe moving to an ElasticSearch would remove this problem, but of course might bring some others...
Don't know if we can fix the container to first run a migration if necessary

**Comment by oliverhaagh** [comment]
Great, thx! :smile: yea, I think that if we can avoid having to depend on ElasticSearch we should that, especially after all their recent license drama...
We could do that, but on the other hand that'll also add more complexity to the container itself, so I think that to begin with it will probably be fine to just have a note about it in the docs.

**Comment by nvasta** [comment]
Added some description in the README for now:
https://github.com/maritimeconnectivity/ServiceRegistry/pull/63

**Comment by oliverhaagh** [comment]
Great, thanks! :smile:
